[project]
name = "caracolswap"
description = "Demonstrates trustless atomic swaps between caracols and Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.caracolswap"

[contracts.caracolswap]
path = "contracts/caracolswap.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
